# Generated by Django 4.2.1 on 2023-05-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comment_id_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_blog',
            new_name='id_block',
        ),
    ]
