# Generated by Django 4.2.1 on 2023-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_id_blog_comment_id_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id_block',
            field=models.PositiveIntegerField(),
        ),
    ]
