# Generated by Django 4.2.1 on 2023-05-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_comment_id_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_block',
            new_name='id_blog',
        ),
    ]
