# Generated by Django 4.2.1 on 2023-05-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_news_options_newscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='courses',
        ),
        migrations.AddField(
            model_name='courses',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
