# Generated by Django 4.2.1 on 2023-05-18 05:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_comment_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclasses',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
