# Generated by Django 4.2.1 on 2023-05-18 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_masterclasses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclasses',
            name='image',
            field=models.ImageField(default=1, upload_to='events_image', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])], verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
