# Generated by Django 4.2.1 on 2023-05-18 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_masterclasses_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(null=True, upload_to='courses_img', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])], verbose_name='Фото курсов'),
        ),
    ]
