# Generated by Django 4.2.1 on 2023-05-19 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_masterclass_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 3, 19, 3, 148830), null=True),
        ),
    ]
