# Generated by Django 4.2.1 on 2023-05-19 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_masterclass_date_created_alter_masterclass_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 9, 14, 51, 280963), null=True),
        ),
    ]
